<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hw1" nsURI="http://www.example.org/hw1" nsPrefix="hw1">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Patient" eSuperTypes="#//Person">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv1_AllBillsMustHaveReceptionist"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv1_AllBillsMustHaveReceptionist" value="&#xA;&#x9;&#x9;&#x9;self.issuedFor->forAll(bill | bill.issuedBy.oclIsTypeOf(Receptionist) and bill.issuedBy->size() = 1)"/>
    </eAnnotations>
    <eOperations name="viewMedicalHistory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="bookAppointment"/>
    <eOperations name="requestLabTest"/>
    <eOperations name="payBill">
      <eParameters name="amount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="medicalHistory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledFor" upperBound="-1"
        eType="#//Appointment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issuedFor" upperBound="-1"
        eType="#//Billing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patientId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booked" upperBound="-1"
        eType="#//LabTest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goingThrough" upperBound="-1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HospitalEmployee" abstract="true" eSuperTypes="#//Person">
    <eOperations name="getEmployeeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employeeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Appointment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appointmentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Doctor" eSuperTypes="#//HospitalEmployee">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv2_DoctorMustBeAssistedByNurse"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv2_DoctorMustBeAssistedByNurse" value="&#xA;&#x9;&#x9;&#x9;self.performs->forAll(op | op.performedBy = self and op.assistedBy->size() > 0 and op.assistedBy->size() &lt; 4)"/>
    </eAnnotations>
    <eOperations name="performOperation" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="nurse" eType="#//Nurse"/>
    </eOperations>
    <eOperations name="prescribeMedicine">
      <eParameters name="patient" eType="#//Patient"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specialization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performs" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/performedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Receptionist" eSuperTypes="#//HospitalEmployee">
    <eOperations name="initiateBill" eType="#//Billing">
      <eParameters name="service" eType="#//MedicalService"/>
    </eOperations>
    <eOperations name="allotBedToPatient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="patient" eType="#//Patient"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Billing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nurse" eSuperTypes="#//HospitalEmployee">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv3_LabTestAssociation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv3_LabTestAssociation" value="&#xA;&#x9;&#x9;&#x9;if self.conducts->notEmpty() then&#xA;&#x9;&#x9;&#x9;&#x9;self.conducts->exists(test | test.conductedBy = self and test.testId > 0)&#xA;&#x9;&#x9;&#x9;else true&#xA;&#x9;&#x9;&#x9;endif"/>
    </eAnnotations>
    <eOperations name="performLabTest" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="test" eType="#//LabTest"/>
    </eOperations>
    <eOperations name="assistDoctor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="operation" eType="#//Operation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conducts" upperBound="-1"
        eType="#//LabTest" containment="true" eOpposite="#//LabTest/conductedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assistsIn" upperBound="-1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Billing">
    <eOperations name="generateBill"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issuedBy" lowerBound="1"
        eType="#//Receptionist" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMedicalService">
    <eOperations name="calculateBill" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MedicalService" abstract="true" eSuperTypes="#//IMedicalService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//MedicalService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performedBy" lowerBound="1"
        eType="#//Doctor" eOpposite="#//Doctor/performs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assistedBy" lowerBound="1"
        upperBound="3" eType="#//Nurse" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabTest" eSuperTypes="#//MedicalService">
    <eOperations name="conductLabTest" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="nurse" eType="#//Nurse"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conductedBy" lowerBound="1"
        eType="#//Nurse" eOpposite="#//Nurse/conducts"/>
  </eClassifiers>
</ecore:EPackage>
